# Generated by Django 5.2 on 2025-07-08 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
        ('users', '0012_remove_user_permission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPermissions',
        ),
    ]
