# Generated by Django 5.2 on 2025-07-08 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_delete_userpermissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permissions',
        ),
    ]
