version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    env_file:
      - ./api/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    ports:
      - "5433:5432"

  backend:
    build: ./api
    container_name: django_backend
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    volumes:
      - ./api:/app
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq
    expose:
      - "8000"
    ports:
      - "8000:8000"

  celery:
    build: ./api
    container_name: celery_worker
    command: celery -A api worker -l info
    restart: unless-stopped
    volumes:
      - ./api:/app
    env_file:
      - .env
    depends_on:
      - backend
      - rabbitmq

  celery-beat:
    build: ./api
    container_name: celery_beat
    command: celery -A api beat -l info
    restart: unless-stopped
    volumes:
      - ./api:/app
    env_file:
      - .env
    depends_on:
      - backend
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_broker
    restart: unless-stopped
    ports:
      - "5673:5672"   # port Celery
      - "15673:15672" # dashboard RabbitMQ

  frontend:
    build: ./front-end
    container_name: react_frontend
    command: npm run dev
    restart: unless-stopped
    volumes:
      - ./front-end:/app
      - /app/node_modules
    env_file:
      - ./front-end/.env
    ports:
      - "5173:5173"


volumes:
  postgres_data:
