# Generated by Django 5.2 on 2025-07-08 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatMateri', '0002_alter_chatmessage_options_and_more'),
        ('materi', '0007_materi_kelas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='topic',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='materi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_session_materi', to='materi.materi'),
        ),
    ]
