# Generated by Django 5.2 on 2025-07-23 06:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelas_siswa', '0001_initial'),
        ('siswa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatKelas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tahun_ajaran', models.CharField(max_length=9)),
                ('kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kelas_siswa.kelassiswa')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_kelas', to='siswa.siswa')),
            ],
            options={
                'unique_together': {('siswa', 'tahun_ajaran')},
            },
        ),
    ]
