# Generated by Django 5.2 on 2025-07-23 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0002_riwayatkelas'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='riwayatkelas',
            table='riwayat_kelas',
        ),
    ]
