# Generated by Django 5.2 on 2025-08-12 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0003_alter_riwayatkelas_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siswa',
            name='kelas_sekarang',
        ),
        migrations.DeleteModel(
            name='RiwayatKelas',
        ),
    ]
