# Generated by Django 5.2 on 2025-08-14 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0006_delete_enrollment'),
        ('siswa', '0005_siswa_alamat_siswa_jenis_kelamin_siswa_tanggal_lahir_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Siswa',
        ),
    ]
