# Generated by Django 5.2 on 2025-08-14 01:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kelas_siswa', '0004_kelassiswa_tahun_ajaran_alter_kelassiswa_wali_kelas'),
        ('siswa', '0006_delete_siswa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiswaKelas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='kelas_siswa', to='kelas_siswa.kelassiswa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siswa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'siswa_kelas',
            },
        ),
    ]
