# Generated by Django 5.2 on 2025-08-14 01:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelas_siswa', '0004_kelassiswa_tahun_ajaran_alter_kelassiswa_wali_kelas'),
        ('siswa', '0007_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatKelas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tahun_ajaran', models.CharField(max_length=9)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('lulus', 'Lulus'), ('mengulang', 'Mengulang')], default='aktif', max_length=10)),
                ('tanggal_update', models.DateTimeField(auto_now=True)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_kelas_siswa', to='kelas_siswa.kelassiswa')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_siswa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'riwayat_kelas',
            },
        ),
    ]
