# Generated by Django 5.2 on 2025-08-14 01:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelas_siswa', '0004_kelassiswa_tahun_ajaran_alter_kelassiswa_wali_kelas'),
        ('mapel', '0005_remove_mapel_organization_mapel_idx'),
        ('siswa', '0008_riwayatkelas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiswaMapel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='kelas_siswa_mapel', to='kelas_siswa.kelassiswa')),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mapel_siswa', to='mapel.mapel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siswa_mapel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'siswa_mapel',
            },
        ),
    ]
