# Generated by Django 5.2 on 2025-08-16 03:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kelas_siswa', '0004_kelassiswa_tahun_ajaran_alter_kelassiswa_wali_kelas'),
        ('mapel', '0005_remove_mapel_organization_mapel_idx'),
        ('siswa', '0009_siswamapel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='siswamapel',
            unique_together={('user', 'mapel', 'kelas')},
        ),
    ]
