# Generated by Django 5.2 on 2025-05-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_remove_user_organization_user_organizations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organizations',
            field=models.ManyToManyField(related_name='users', to='users.organization'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['date_joined'], name='date_joined_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['nama'], name='nama_idx'),
        ),
    ]
