# Generated by Django 5.2 on 2025-06-28 04:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapel', '0005_remove_mapel_organization_mapel_idx'),
        ('users', '0006_alter_user_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMapel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mapel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapel.mapel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_mapel',
                'unique_together': {('user', 'mapel')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='user_mapel',
            field=models.ManyToManyField(related_name='user_mapel', through='users.UserMapel', through_fields=('user', 'mapel'), to='mapel.mapel'),
        ),
    ]
