# Generated by Django 5.2 on 2025-07-06 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semester', '0002_alter_semester_semester'),
        ('users', '0007_usermapel_user_user_mapel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermapel',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='semester.semester'),
        ),
    ]
