# Generated by Django 5.2 on 2025-07-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelas_siswa', '0001_initial'),
        ('users', '0009_userkelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_kelas',
            field=models.ManyToManyField(related_name='user_kelas', through='users.UserKelas', through_fields=('user', 'kelas'), to='kelas_siswa.kelassiswa'),
        ),
    ]
