# Generated by Django 5.2 on 2025-07-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
        ('users', '0010_user_user_kelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.ManyToManyField(related_name='user_permission', through='permissions.UserPermissions', through_fields=('user', 'permission'), to='permissions.permissions'),
        ),
    ]
