# Generated by Django 5.2 on 2025-07-08 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='permission',
        ),
    ]
