# Generated by Django 5.2 on 2025-07-08 08:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0004_initial'),
        ('users', '0012_remove_user_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCustomPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='permissions.custompermission')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_custom_permission',
                'unique_together': {('user', 'permission')},
            },
        ),
    ]
