# Generated by Django 5.2 on 2025-07-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0004_initial'),
        ('users', '0013_usercustompermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_permission',
            field=models.ManyToManyField(related_name='user_permissions', through='users.UserCustomPermission', through_fields=('user', 'permission'), to='permissions.custompermission'),
        ),
    ]
