# Generated by Django 5.2 on 2025-07-08 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_custom_permission'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercustompermission',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='user',
            name='custom_permission',
        ),
        migrations.RemoveField(
            model_name='usercustompermission',
            name='user',
        ),
    ]
