# Generated by Django 5.2 on 2025-07-08 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('permissions', '0004_initial'),
        ('users', '0015_alter_usercustompermission_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustompermission',
            name='user_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AlterUniqueTogether(
            name='usercustompermission',
            unique_together={('user_group', 'permission')},
        ),
    ]
