# Generated by Django 5.2 on 2025-07-23 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_usercustompermission_user_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_kelas',
        ),
        migrations.AlterUniqueTogether(
            name='usermapel',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usermapel',
            name='mapel',
        ),
        migrations.RemoveField(
            model_name='usermapel',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='usermapel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_mapel',
        ),
        migrations.DeleteModel(
            name='UserKelas',
        ),
        migrations.DeleteModel(
            name='UserMapel',
        ),
    ]
