# Generated by Django 5.2 on 2025-08-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_user_user_kelas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alamat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('p', 'Perempuan')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tanggal_lahir',
            field=models.DateField(blank=True, null=True),
        ),
    ]
