# Generated by Django 5.2 on 2025-08-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_alamat_user_jenis_kelamin_user_tanggal_lahir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=10, null=True),
        ),
    ]
