# Generated by Django 5.2 on 2025-06-18 07:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_remove_user_organizations_user_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tahun', models.CharField(max_length=10)),
                ('semester', models.CharField(choices=[('ganjil', 'Ganjil'), ('genap', 'Genap')], default='ganjil', max_length=10)),
                ('is_aktif', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='semester_organization', to='users.organization')),
            ],
            options={
                'db_table': 'semester',
                'unique_together': {('tahun', 'semester', 'organization')},
            },
        ),
    ]
