# Generated by Django 5.2 on 2025-06-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semester', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.CharField(choices=[('ganjil', 'Ganjil'), ('genap', 'Genap')], max_length=10),
        ),
    ]
