# Generated by Django 5.2 on 2025-07-23 07:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guru', '0001_initial'),
        ('siswa', '0003_alter_riwayatkelas_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mengajar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guru.mengajar')),
                ('siswa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siswa.siswa')),
            ],
            options={
                'db_table': 'enrollment',
                'unique_together': {('siswa', 'mengajar')},
            },
        ),
    ]
