# Generated by Django 5.2 on 2025-08-12 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
        ('semester', '0002_alter_semester_semester'),
        ('siswa', '0005_siswa_alamat_siswa_jenis_kelamin_siswa_tanggal_lahir_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_semester', to='semester.semester'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='siswa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_siswa', to='siswa.siswa'),
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='mengajar',
        ),
    ]
