# Generated by Django 5.2 on 2025-08-12 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_alter_enrollment_unique_together_enrollment_semester_and_more'),
        ('kelas_siswa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='kelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_kelas', to='kelas_siswa.kelassiswa'),
        ),
    ]
