# Generated by Django 5.2 on 2025-08-12 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_enrollment_kelas'),
        ('kelas_siswa', '0001_initial'),
        ('semester', '0002_alter_semester_semester'),
        ('siswa', '0005_siswa_alamat_siswa_jenis_kelamin_siswa_tanggal_lahir_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('siswa', 'kelas', 'semester')},
        ),
    ]
