# Generated by Django 5.2 on 2025-08-14 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0005_enrollment_created_at_enrollment_mapel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
