# Generated by Django 5.2 on 2025-05-15 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapel', '0002_mapel_organization'),
        ('materi', '0001_initial'),
        ('users', '0005_remove_user_organizations_user_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='materi',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.organization'),
        ),
        migrations.AddIndex(
            model_name='materi',
            index=models.Index(fields=['created_by'], name='created_by_idx'),
        ),
        migrations.AddIndex(
            model_name='materi',
            index=models.Index(fields=['organization'], name='organization_idx'),
        ),
    ]
