# Generated by Django 5.2 on 2025-05-15 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materi', '0002_materi_organization_materi_created_by_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='materi',
            name='created_by_idx',
        ),
        migrations.RemoveIndex(
            model_name='materi',
            name='organization_idx',
        ),
    ]
