# Generated by Django 5.2 on 2025-05-16 07:30


import materi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materi', '0003_remove_materi_created_by_idx_and_more'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='materi',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=materi.models.unique_file_path),
        ),
    ]
