# Generated by Django 5.2 on 2025-06-18 07:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materi', '0004_alter_materi_content_alter_materi_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materi',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
