# Generated by Django 5.2 on 2025-06-22 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materi', '0005_alter_materi_content'),
        ('semester', '0002_alter_semester_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='materi',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='semester.semester'),
        ),
    ]
