# Generated by Django 5.2 on 2025-07-02 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelas_siswa', '0001_initial'),
        ('materi', '0006_materi_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='materi',
            name='kelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kelas_siswa.kelassiswa'),
        ),
    ]
