# Generated by Django 5.2 on 2025-07-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materi', '0007_materi_kelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materi',
            name='content',
            field=models.TextField(),
        ),
    ]
