# Generated by Django 5.2 on 2025-07-23 07:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kelas_siswa', '0001_initial'),
        ('mapel', '0005_remove_mapel_organization_mapel_idx'),
        ('semester', '0002_alter_semester_semester'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mengajar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tahun_ajaran', models.CharField(max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kelas_siswa.kelassiswa')),
                ('mapel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapel.mapel')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='semester.semester')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mengajar',
                'unique_together': {('user', 'mapel', 'kelas', 'tahun_ajaran', 'semester')},
            },
        ),
    ]
