# Generated by Django 5.2 on 2025-08-12 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0003_guru'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mengajar',
            unique_together=set(),
        ),
    ]
