# Generated by Django 5.2 on 2025-08-12 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0004_alter_mengajar_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mengajar',
            name='user',
        ),
        migrations.AddField(
            model_name='mengajar',
            name='guru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guru_mengajar', to='guru.guru'),
        ),
    ]
