# Generated by Django 5.2 on 2025-08-12 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0005_remove_mengajar_user_mengajar_guru'),
        ('kelas_siswa', '0001_initial'),
        ('mapel', '0005_remove_mapel_organization_mapel_idx'),
        ('semester', '0002_alter_semester_semester'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mengajar',
            unique_together={('guru', 'mapel', 'kelas', 'tahun_ajaran', 'semester')},
        ),
    ]
