# Generated by Django 5.2 on 2025-08-12 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0006_alter_mengajar_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='mengajar',
            name='hari',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mengajar',
            name='jam_mulai',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mengajar',
            name='jam_selesai',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
