# Generated by Django 5.2 on 2025-08-13 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0007_mengajar_hari_mengajar_jam_mulai_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mengajar',
            name='guru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guru_mengajar', to=settings.AUTH_USER_MODEL),
        ),
    ]
