# Generated by Django 5.2 on 2025-08-21 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0008_alter_mengajar_guru'),
        ('kelas_siswa', '0004_kelassiswa_tahun_ajaran_alter_kelassiswa_wali_kelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mengajar',
            name='kelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guru_mengajar_kelas', to='kelas_siswa.kelassiswa'),
        ),
    ]
