# Generated by Django 5.2 on 2025-05-15 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapel', '0001_initial'),
        ('users', '0004_alter_user_organizations_user_date_joined_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapel',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.organization'),
        ),
    ]
