# Generated by Django 5.2 on 2025-05-15 00:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapel', '0003_mapel_created_by'),
        ('users', '0005_remove_user_organizations_user_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mapel',
            index=models.Index(fields=['organization'], name='organization_mapel_idx'),
        ),
    ]
