# Generated by Django 5.2 on 2025-05-15 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapel', '0004_mapel_organization_mapel_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mapel',
            name='organization_mapel_idx',
        ),
    ]
