# Generated by Django 5.2 on 2025-06-28 01:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mapel', '0005_remove_mapel_organization_mapel_idx'),
        ('semester', '0002_alter_semester_semester'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField(help_text='Durasi ujian dalam detik')),
                ('score', models.FloatField(blank=True, null=True)),
                ('attempt', models.IntegerField(default=1)),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapel.mapel')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semester.semester')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exam_result',
            },
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('selected_choice', models.CharField(max_length=10)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='ujian.examresult')),
            ],
            options={
                'db_table': 'exam_answer',
            },
        ),
    ]
