# Generated by Django 5.2 on 2025-06-28 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soal', '0004_soal_organization_soal_semester'),
        ('ujian', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examanswer',
            name='question_number',
        ),
        migrations.AddField(
            model_name='examanswer',
            name='soal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soal.soal'),
        ),
    ]
