# Generated by Django 5.2 on 2025-07-06 08:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelas_siswa', '0001_initial'),
        ('mapel', '0005_remove_mapel_organization_mapel_idx'),
        ('ujian', '0002_remove_examanswer_question_number_examanswer_soal'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='kelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kelas_siswa.kelassiswa'),
        ),
        migrations.CreateModel(
            name='Ujian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=100)),
                ('jenis_ujian', models.CharField(choices=[('UTS', 'UTS'), ('UAS', 'UAS')], default='UTS', max_length=10)),
                ('tanggal', models.DateField()),
                ('waktu_mulai', models.TimeField()),
                ('durasi', models.IntegerField(help_text='Durasi ujian dalam detik')),
                ('bobot_nilai', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('passing_grade', models.DecimalField(decimal_places=2, default=70.0, max_digits=5)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kelas_siswa.kelassiswa')),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapel.mapel')),
            ],
            options={
                'db_table': 'ujian',
            },
        ),
    ]
