# Generated by Django 5.2 on 2025-07-06 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujian', '0003_examresult_kelas_ujian'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='ujian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ujian.ujian'),
        ),
    ]
