# Generated by Django 5.2 on 2025-07-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujian', '0004_examresult_ujian'),
    ]

    operations = [
        migrations.AddField(
            model_name='ujian',
            name='tanggal_akhir',
            field=models.DateField(blank=True, null=True),
        ),
    ]
