# Generated by Django 5.2 on 2025-07-06 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujian', '0005_ujian_tanggal_akhir'),
        ('users', '0010_user_user_kelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='ujian',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.organization'),
        ),
    ]
