# Generated by Django 5.2 on 2025-07-07 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semester', '0002_alter_semester_semester'),
        ('ujian', '0006_ujian_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='ujian',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='semester.semester'),
        ),
    ]
