# Generated by Django 5.2 on 2025-07-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ujian', '0007_ujian_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresult',
            name='kelas',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='mapel',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='semester',
        ),
        migrations.AddField(
            model_name='examresult',
            name='waktu_mulai',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Durasi ujian dalam detik', null=True),
        ),
    ]
