# Generated by Django 5.2 on 2025-07-08 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ujian', '0008_remove_examresult_kelas_remove_examresult_mapel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamAnswer',
        ),
    ]
