# Generated by Django 5.2 on 2025-07-08 01:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soal', '0008_remove_soal_mapel'),
        ('ujian', '0009_delete_examanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_choice', models.CharField(max_length=10)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='ujian.examresult')),
                ('soal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soal.soal')),
            ],
            options={
                'db_table': 'exam_answer',
            },
        ),
    ]
