# Generated by Django 5.2 on 2025-08-12 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0006_alter_mengajar_unique_together'),
        ('kelas_siswa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kelassiswa',
            name='wali_kelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wali_kelas', to='guru.guru'),
        ),
    ]
