# Generated by Django 5.2 on 2025-08-13 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelas_siswa', '0002_kelassiswa_wali_kelas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelassiswa',
            name='wali_kelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wali_kelas', to=settings.AUTH_USER_MODEL),
        ),
    ]
