# Generated by Django 5.2 on 2025-06-11 06:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mapel', '0005_remove_mapel_organization_mapel_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipe_soal', models.CharField(choices=[('pilihan_ganda', 'Pilihan Ganda'), ('esai', 'Esai')], max_length=20)),
                ('pertanyaan', models.TextField()),
                ('pilihan', models.JSONField(blank=True, null=True)),
                ('jawaban_benar', models.TextField(blank=True, null=True)),
                ('tingkat_kesulitan', models.CharField(blank=True, choices=[('mudah', 'Mudah'), ('sedang', 'Sedang'), ('sulit', 'Sulit')], default='mudah', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soal_mapel', to='mapel.mapel')),
            ],
            options={
                'db_table': 'soal',
            },
        ),
    ]
