# Generated by Django 5.2 on 2025-06-18 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semester', '0001_initial'),
        ('soal', '0003_alter_soal_created_by'),
        ('users', '0005_remove_user_organizations_user_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='soal',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='soal_organization', to='users.organization'),
        ),
        migrations.AddField(
            model_name='soal',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='soal_semester', to='semester.semester'),
        ),
    ]
