# Generated by Django 5.2 on 2025-06-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soal', '0004_soal_organization_soal_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='soal',
            name='gambar',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soal',
            name='tabel',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
