# Generated by Django 5.2 on 2025-07-01 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelas_siswa', '0001_initial'),
        ('soal', '0005_soal_gambar_soal_tabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='soal',
            name='kelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='soal_kelas', to='kelas_siswa.kelassiswa'),
        ),
    ]
