# Generated by Django 5.2 on 2025-07-07 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soal', '0006_soal_kelas'),
        ('ujian', '0006_ujian_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soal',
            name='kelas',
        ),
        migrations.RemoveField(
            model_name='soal',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='soal',
            name='semester',
        ),
        migrations.AddField(
            model_name='soal',
            name='ujian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='soal_ujian', to='ujian.ujian'),
        ),
    ]
