# Generated by Django 5.2 on 2025-07-07 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soal', '0007_remove_soal_kelas_remove_soal_organization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soal',
            name='mapel',
        ),
    ]
